// Script to add missing lessons to lessonContent.js
const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'src', 'data', 'lessonContent.js');
let content = fs.readFileSync(file, 'utf8');

// All lessons to add - grouped by subject
const newLessons = {
  // ─── GEOGRAPHY CM1-5e ────────────────────────────────────────
  'geo-cm1-2': { title: 'CM1 - Activites economiques', pages: [
    { emoji: '🏭', title: 'L\'agriculture', content: 'La France est le 1er pays agricole de l\'UE. Ble en Beauce, vignes en Bourgogne, elevage en Bretagne. L\'agriculture nourrit la population et exporte dans le monde entier.', highlights: ['1er pays agricole de l\'UE', 'Cereales, vignes, elevage', 'Agriculture bio en croissance', 'Exportation mondiale'], tip: 'La France produit 300 sortes de fromages ! C\'est le pays qui en produit le plus au monde.' },
    { emoji: '🏗️', title: 'L\'industrie', content: 'L\'industrie transforme les matieres premieres en produits. Automobile (Renault, Peugeot), aeronautique (Airbus), agroalimentaire (Danone), luxe (LVMH). Les usines sont souvent pres des villes.', highlights: ['Automobile, aeronautique', 'Agroalimentaire, luxe', 'Zones industrielles', 'Emplois ouvriers et ingenieurs'], tip: 'Airbus assemble ses avions a Toulouse. Les pieces viennent de toute l\'Europe. C\'est la cooperation europeenne en action !' },
    { emoji: '🛍️', title: 'Les services', content: 'Les services representent 80% de l\'economie francaise : commerces, banques, hopitaux, ecoles, tourisme, informatique. Le secteur tertiaire emploie la grande majorite des travailleurs.', highlights: ['80% de l\'economie', 'Commerce, sante, education', 'Tourisme : 1ere destination mondiale', 'Numerique en croissance'], tip: 'La France est la 1ere destination touristique au monde avec 90 millions de visiteurs par an. La Tour Eiffel, le Louvre, Versailles attirent le monde entier.' },
    { emoji: '🌾', title: 'Secteurs primaire, secondaire, tertiaire', content: 'L\'economie se divise en 3 secteurs. Primaire : agriculture, peche, mines. Secondaire : industrie, construction. Tertiaire : services, commerce. En France, le tertiaire domine largement.', highlights: ['Primaire : exploiter la nature', 'Secondaire : transformer', 'Tertiaire : services', 'Tertiaire = 80% des emplois'], tip: 'Il y a 200 ans, 80% des Francais etaient agriculteurs. Aujourd\'hui, c\'est seulement 3%. La mecanisation a tout change.' },
    { emoji: '🌍', title: 'Les echanges commerciaux', content: 'La France commerce avec le monde entier. Elle exporte des avions, du vin, du luxe, des cereales. Elle importe du petrole, de l\'electronique, des vetements. L\'UE est son 1er partenaire commercial.', highlights: ['Exportations : aeronautique, luxe, vin', 'Importations : petrole, electronique', 'UE : 1er partenaire', 'Balance commerciale'], tip: 'Les produits de luxe francais (Chanel, Louis Vuitton, Hermes) sont tres demandes en Asie et aux Etats-Unis.' },
  ]},
  'geo-cm1-3': { title: 'CM1 - Transports et mobilite', pages: [
    { emoji: '🚂', title: 'Les transports en France', content: 'La France a un reseau de transports varie : routes et autoroutes, voies ferrees (TGV), aeroports, ports. Le TGV relie les grandes villes a grande vitesse : Paris-Lyon en 2h.', highlights: ['TGV : 320 km/h', 'Autoroutes : 12 000 km', 'Aeroports : Roissy, Orly', 'Ports : Marseille, Le Havre'], tip: 'Le TGV est une invention francaise (1981). Il a battu le record de vitesse sur rail : 574,8 km/h en 2007 !' },
    { emoji: '🚗', title: 'Se deplacer au quotidien', content: 'La voiture est le moyen de transport le plus utilise en France (70% des deplacements). En ville, les transports en commun (bus, metro, tramway) sont une alternative. Le velo se developpe.', highlights: ['Voiture : 70% des deplacements', 'Bus, metro, tramway en ville', 'Velo en forte croissance', 'Covoiturage'], tip: 'Les bouchons coutent 20 milliards d\'euros par an a la France en temps perdu et en pollution. Les transports en commun sont une solution !' },
    { emoji: '✈️', title: 'Les transports a longue distance', content: 'L\'avion relie les grandes villes et les continents. Le train (TGV, Eurostar, Thalys) est ideal pour les distances moyennes. Le bateau transporte 90% des marchandises mondiales.', highlights: ['Avion : rapide mais polluant', 'TGV : rapide et moins polluant', 'Bateau : 90% des marchandises', 'Eurostar : Paris-Londres en 2h15'], tip: 'Pour Paris-Lyon, le TGV est plus rapide que l\'avion (en comptant le temps a l\'aeroport) et 30 fois moins polluant.' },
    { emoji: '🚲', title: 'Les mobilites douces', content: 'Marche, velo, trottinette : les mobilites douces sont bonnes pour la sante et l\'environnement. Les villes amenagent des pistes cyclables et des zones pietonnes.', highlights: ['Velo : sain et ecologique', 'Pistes cyclables en croissance', 'Zones pietonnes en centre-ville', 'Trottinettes electriques'], tip: 'Amsterdam est la capitale mondiale du velo : 800 000 velos pour 850 000 habitants. La France s\'en inspire !' },
    { emoji: '🌿', title: 'Se deplacer durablement', content: 'Les transports sont le 1er secteur emetteur de CO2 en France. Pour reduire la pollution : transports en commun, covoiturage, velo, vehicules electriques. Chaque choix compte !', highlights: ['Transports = 30% du CO2 francais', 'Vehicules electriques', 'Covoiturage et autopartage', 'Choisir le bon moyen de transport'], tip: '1 km en voiture = 200g de CO2. 1 km en TGV = 3g. 1 km a velo = 0g. Le choix du transport fait une vraie difference !' },
  ]},
  'geo-cm1-4': { title: 'CM1 - L\'Europe', pages: [
    { emoji: '🇪🇺', title: 'Le continent europeen', content: 'L\'Europe est un continent de 10,5 millions de km² avec environ 750 millions d\'habitants. Elle s\'etend de l\'Atlantique a l\'Oural, de la Scandinavie a la Mediterranee. 50 pays environ.', highlights: ['750 millions d\'habitants', '~50 pays', 'De l\'Atlantique a l\'Oural', 'Climat tempere en majorite'], tip: 'L\'Europe n\'est pas une ile : c\'est la partie occidentale du continent eurasiatique. La frontiere avec l\'Asie est l\'Oural (chaine de montagnes en Russie).' },
    { emoji: '🗺️', title: 'Les pays d\'Europe', content: 'Les plus grands : Russie, Ukraine, France. Les plus petits : Vatican, Monaco, Saint-Marin. Chaque pays a sa langue, sa culture, son histoire. La diversite est une richesse de l\'Europe.', highlights: ['Russie : le plus grand (en partie)', 'Vatican : le plus petit', 'France : le plus grand de l\'UE', 'Diversite de langues et cultures'], tip: 'En Europe, on parle plus de 200 langues ! Les 3 familles principales : langues romanes (francais, espagnol), germaniques (anglais, allemand), slaves (russe, polonais).' },
    { emoji: '🏛️', title: 'L\'Union europeenne', content: 'L\'UE regroupe 27 pays qui cooperent economiquement et politiquement. L\'euro est la monnaie de 20 pays. L\'espace Schengen permet de voyager sans passeport entre 27 pays.', highlights: ['27 pays membres', 'Euro : 20 pays', 'Espace Schengen', 'Libre circulation'], tip: 'Tous les pays d\'Europe ne sont pas dans l\'UE. La Suisse, la Norvege, le Royaume-Uni (Brexit) n\'en font pas partie.' },
    { emoji: '🌍', title: 'Les paysages d\'Europe', content: 'L\'Europe a des paysages tres varies : fjords de Norvege, plaines d\'Europe centrale, montagnes des Alpes, iles grecques, forets de Finlande, volcans d\'Islande.', highlights: ['Alpes : plus haute chaine', 'Fjords : Norvege', 'Plaines : Europe centrale', 'Mediterranee : climat chaud'], tip: 'Le plus haut sommet d\'Europe est le Mont Elbrouz (5 642 m) en Russie. En Europe occidentale, c\'est le Mont-Blanc (4 808 m).' },
    { emoji: '🤝', title: 'Vivre en Europe', content: 'Les Europeens partagent des valeurs : democratie, droits de l\'Homme, etat de droit. Le programme Erasmus permet aux etudiants d\'etudier dans un autre pays. Les Europeens voyagent facilement.', highlights: ['Democratie et droits de l\'Homme', 'Erasmus : etudier a l\'etranger', 'Voyager sans frontiere', 'Cooperation et solidarite'], tip: 'Avec le programme Erasmus, tu pourras etudier 6 mois a 1 an dans une universite en Espagne, en Allemagne, en Italie...' },
  ]},
  'geo-cm1-5': { title: 'CM1 - Espaces touristiques', pages: [
    { emoji: '🗼', title: 'La France touristique', content: 'La France est la 1ere destination touristique mondiale : Paris, la Cote d\'Azur, les chateaux de la Loire, le Mont-Saint-Michel, les stations de ski. Le tourisme represente 8% du PIB.', highlights: ['90 millions de visiteurs/an', 'Paris : ville la plus visitee', 'Cote d\'Azur, Loire, ski', '8% du PIB'], tip: 'Le Louvre est le musee le plus visite au monde avec 10 millions de visiteurs par an. La Joconde y est pour beaucoup !' },
    { emoji: '🏖️', title: 'Le tourisme balneaire', content: 'Les cotes francaises attirent des millions de touristes l\'ete : Cote d\'Azur, cotes bretonnes, bassin d\'Arcachon, Corse. Le soleil, la mer, les plages sont les premieres motivations.', highlights: ['Cote d\'Azur : Nice, Cannes', 'Bretagne : cotes sauvages', 'Corse : ile de beaute', 'Bassin d\'Arcachon : dune du Pilat'], tip: 'La dune du Pilat est la plus haute dune d\'Europe : 106 m de haut ! Elle avance de 1 a 5 m par an vers la foret.' },
    { emoji: '⛷️', title: 'Le tourisme de montagne', content: 'Les Alpes et les Pyrenees sont les grandes regions de ski en France. L\'ete, on y fait de la randonnee, du VTT, de l\'escalade. Le tourisme de montagne represente 10 milliards d\'euros par an.', highlights: ['Ski l\'hiver, rando l\'ete', 'Alpes : plus grandes stations', 'Pyrenees : plus sauvages', '10 milliards d\'euros/an'], tip: 'Avec le rechauffement climatique, la neige se fait plus rare. Les stations de basse altitude doivent se reinventer avec des activites d\'ete.' },
    { emoji: '🏰', title: 'Le tourisme culturel', content: 'Musees, chateaux, cathedrales, festivals : le patrimoine francais est immense. Les chateaux de la Loire, le Mont-Saint-Michel, les grottes de Lascaux attirent des millions de visiteurs.', highlights: ['45 000 monuments historiques', 'Chateaux de la Loire', 'Mont-Saint-Michel', 'Festivals : Avignon, Cannes'], tip: 'La France a 49 sites inscrits au patrimoine mondial de l\'UNESCO, le 4e total mondial.' },
    { emoji: '🌿', title: 'Le tourisme durable', content: 'Le tourisme de masse a des impacts negatifs : pollution, degradation des sites, surfacite. Le tourisme durable cherche a respecter l\'environnement et les populations locales.', highlights: ['Impact du tourisme de masse', 'Ecotourisme : respecter la nature', 'Agritourisme : fermes et terroir', 'Tourisme responsable'], tip: 'Prefere les transports doux, les hebergements locaux, les produits du terroir. C\'est meilleur pour la planete et pour les habitants !' },
  ]},
  'geo-cm2-2': { title: 'CM2 - Developpement durable', pages: [
    { emoji: '🌍', title: 'Qu\'est-ce que le developpement durable ?', content: 'Le developpement durable repond aux besoins du present sans compromettre ceux des generations futures. Il repose sur 3 piliers : economique (prosperer), social (bien vivre), environnemental (preserver).', highlights: ['3 piliers : economie, social, environnement', 'Penser aux generations futures', '17 objectifs de l\'ONU (ODD)', 'Agir local, penser global'], tip: 'Les 17 ODD (Objectifs de Developpement Durable) de l\'ONU guident les pays vers un monde meilleur d\'ici 2030 : pauvrete, education, climat, egalite...' },
    { emoji: '♻️', title: 'Recycler et economiser', content: 'Trier ses dechets, recycler, composter, economiser l\'eau et l\'electricite : chaque geste compte. Les 3 R : Reduire, Reutiliser, Recycler.', highlights: ['Reduire : consommer moins', 'Reutiliser : donner une 2e vie', 'Recycler : transformer les dechets', 'Composter : dechets organiques'], tip: 'Un Francais produit 580 kg de dechets par an. En triant et en reduisant, on peut facilement diviser ce chiffre par 2.' },
    { emoji: '💧', title: 'L\'eau, une ressource precieuse', content: 'L\'eau douce ne represente que 3% de l\'eau sur Terre, et seulement 1% est accessible. Economies d\'eau, lutte contre la pollution, partage equitable : l\'eau est l\'enjeu du siecle.', highlights: ['3% d\'eau douce sur Terre', '1% accessible', 'Gaspillage : 150 L/jour/Francais', 'Pollution des nappes et rivieres'], tip: 'Prendre une douche au lieu d\'un bain economise 100 L d\'eau. Fermer le robinet en se brossant les dents economise 12 L.' },
    { emoji: '⚡', title: 'Les energies', content: 'Les energies fossiles (petrole, gaz, charbon) polluent et s\'epuisent. Les energies renouvelables (solaire, eolien, hydraulique) sont l\'avenir. La France produit 70% de son electricite avec le nucleaire.', highlights: ['Fossiles : polluantes et limitees', 'Renouvelables : solaire, eolien, hydro', 'Nucleaire : 70% en France', 'Transition energetique'], tip: 'L\'energie la plus propre est celle qu\'on ne consomme pas ! Eteindre les lumieres, isoler sa maison, baisser le chauffage : des gestes simples mais efficaces.' },
    { emoji: '🌿', title: 'Agir pour la planete', content: 'Chacun peut agir : transports doux, consommation responsable, zero dechet, alimentation locale et de saison. Les eco-gestes au quotidien font une vraie difference.', highlights: ['Manger local et de saison', 'Transports doux : velo, marche', 'Reduire les emballages', 'Economiser energie et eau'], tip: 'Un repas avec des produits locaux et de saison emet 5 fois moins de CO2 qu\'un repas avec des produits importes par avion.' },
  ]},
  'geo-cm2-3': { title: 'CM2 - Recycler et economiser', pages: [
    { emoji: '🗑️', title: 'Le tri des dechets', content: 'Trier ses dechets permet de les recycler. Poubelle jaune : plastiques, cartons, metaux. Poubelle verte : verre. Poubelle grise : dechets non recyclables. Le compost pour les dechets organiques.', highlights: ['Jaune : plastique, carton, metal', 'Verte : verre', 'Grise : non recyclable', 'Compost : dechets organiques'], tip: 'Le verre se recycle a l\'infini sans perdre sa qualite. Une bouteille en verre peut redevenir une bouteille a l\'infini !' },
    { emoji: '♻️', title: 'Que deviennent nos dechets ?', content: 'Les dechets tries sont envoyes dans des centres de tri, puis dans des usines de recyclage. Le plastique devient du tissu polaire, le papier redevient du papier, le verre du verre. Le non-recyclable est incinere ou enfoui.', highlights: ['Centre de tri : separer', 'Usine de recyclage : transformer', 'Incineration : bruler (energie)', 'Enfouissement : enterrer (polluant)'], tip: '27 bouteilles en plastique recyclees = 1 pull en polaire. Le recyclage donne une seconde vie aux dechets !' },
    { emoji: '🌱', title: 'Reduire ses dechets', content: 'Le meilleur dechet est celui qu\'on ne produit pas ! Acheter en vrac, utiliser des sacs reutilisables, eviter les produits sur-emballes, reparer au lieu de jeter.', highlights: ['Acheter en vrac', 'Sacs reutilisables', 'Gourde au lieu de bouteilles', 'Reparer plutot que jeter'], tip: 'Le mouvement "zero dechet" propose de vivre en produisant le minimum de dechets. Certaines familles tiennent dans un bocal !' },
    { emoji: '💧', title: 'Economiser l\'eau', content: 'L\'eau est precieuse. Economies simples : douche courte, robinet ferme, chasse d\'eau economique, arrosage le soir. Recuperer l\'eau de pluie pour le jardin est une excellente idee.', highlights: ['Douche vs bain : 60L vs 200L', 'Fermer le robinet', 'Recuperer l\'eau de pluie', 'Arroser le soir (moins d\'evaporation)'], tip: 'Un robinet qui goutte = 120 litres d\'eau gaspilles par jour = 44 000 litres par an. Repare les fuites !' },
    { emoji: '💡', title: 'Economiser l\'energie', content: 'Eteindre les lumieres, baisser le chauffage d\'1°C (= -7% d\'energie), debrancher les appareils en veille, utiliser des ampoules LED. Chaque geste economise de l\'energie ET de l\'argent.', highlights: ['-1°C de chauffage = -7% d\'energie', 'LED : 5x moins d\'electricite', 'Eteindre les appareils en veille', 'Isoler sa maison'], tip: 'Les appareils en veille (TV, box, chargeurs) consomment 10% de l\'electricite d\'un foyer. Debranche-les !' },
  ]},
  'geo-cm2-4': { title: 'CM2 - Les continents et oceans', pages: [
    { emoji: '🌍', title: 'Les 6 continents', content: 'La Terre a 6 continents : Afrique, Amerique, Antarctique, Asie, Europe, Oceanie. L\'Asie est le plus grand et le plus peuple. L\'Antarctique est le seul sans habitants permanents.', highlights: ['Asie : le plus grand et peuple', 'Afrique : 2e en taille', 'Amerique : Nord et Sud', 'Antarctique : glace et froid extreme'], tip: 'L\'Asie a plus de 4,5 milliards d\'habitants, soit 60% de la population mondiale. La Chine et l\'Inde a elles seules representent 1/3 de l\'humanite.' },
    { emoji: '🌊', title: 'Les 5 oceans', content: 'Les 5 oceans : Pacifique (le plus grand), Atlantique, Indien, Arctique (le plus petit), Antarctique. Ils couvrent 71% de la surface terrestre. Les oceans regulrent le climat.', highlights: ['Pacifique : le plus grand', 'Atlantique : entre Amerique et Europe', 'Indien : entre Afrique et Asie', '71% de la surface terrestre'], tip: 'L\'ocean Pacifique est si grand qu\'il couvre plus de surface que tous les continents reunis !' },
    { emoji: '📊', title: 'La repartition de la population', content: '8 milliards d\'humains vivent sur Terre, mais la repartition est tres inegale. L\'Asie concentre 60% de la population. Les deserts, les poles et les hautes montagnes sont quasi vides.', highlights: ['8 milliards d\'habitants', 'Asie : 60% de la pop. mondiale', 'Foyers de peuplement : Asie, Europe', 'Espaces vides : deserts, poles'], tip: 'Si on mettait tous les humains debout cote a cote, ils tiendraient dans la ville de Los Angeles. On n\'est pas si nombreux a l\'echelle de la planete !' },
    { emoji: '🌡️', title: 'Les grandes zones climatiques', content: 'La Terre a 5 grandes zones climatiques : tropicale (chaud et humide), aride (deserts), temperee (saisons marquees), continentale (grands ecarts), polaire (froid extreme).', highlights: ['Tropicale : pres de l\'equateur', 'Aride : deserts chauds et froids', 'Temperee : Europe, Amerique du Nord', 'Polaire : Arctique et Antarctique'], tip: 'La latitude (distance a l\'equateur) est le 1er facteur du climat. Plus on s\'eloigne de l\'equateur, plus il fait froid.' },
    { emoji: '🗺️', title: 'Se reperer sur un planisphere', content: 'Le planisphere est une carte du monde a plat. L\'equateur separe les hemispheres Nord et Sud. Le meridien de Greenwich separe Est et Ouest. La latitude et la longitude permettent de situer tout point sur Terre.', highlights: ['Equateur : ligne 0° de latitude', 'Meridien de Greenwich : 0° de longitude', 'Hemispheres Nord et Sud', 'Tropiques et cercles polaires'], tip: 'Toute carte du monde deforme la realite car on met une sphere sur une surface plate. Le Groenland parait immense mais est 14 fois plus petit que l\'Afrique !' },
  ]},
  'geo-cm2-5': { title: 'CM2 - Outre-mer et francophonie', pages: [
    { emoji: '🌴', title: 'Les territoires d\'outre-mer', content: 'La France possede des territoires sur tous les continents : Guadeloupe, Martinique (Caraibes), Guyane (Amerique du Sud), Reunion, Mayotte (ocean Indien), Nouvelle-Caledonie, Polynesie (Pacifique).', highlights: ['5 DROM : Guadeloupe, Martinique, Guyane, Reunion, Mayotte', 'COM : Polynesie, Nouvelle-Caledonie', 'Presents sur tous les oceans', '2,8 millions d\'habitants outre-mer'], tip: 'La Guyane est le plus grand departement francais en superficie : 84 000 km² (plus grand que l\'Autriche), mais seulement 300 000 habitants.' },
    { emoji: '🌺', title: 'Diversite des outre-mer', content: 'Chaque territoire a ses specificites : la Reunion a un volcan actif, la Guyane une foret equatoriale immense, la Polynesie des atolls paradisiaques. Le climat est tropical ou equatorial.', highlights: ['Reunion : Piton de la Fournaise', 'Guyane : foret amazonienne', 'Polynesie : 118 iles', 'Biodiversite exceptionnelle'], tip: 'La Guyane abrite le centre spatial de Kourou. Les fusees Ariane decollent pres de l\'equateur car la rotation de la Terre leur donne un "elan" supplementaire.' },
    { emoji: '🗣️', title: 'La francophonie', content: 'La francophonie regroupe les 321 millions de personnes qui parlent francais dans le monde. L\'Organisation Internationale de la Francophonie (OIF) compte 88 Etats et gouvernements membres.', highlights: ['321 millions de francophones', '88 membres de l\'OIF', 'Afrique : continent le plus francophone', '5e langue la plus parlee'], tip: 'D\'ici 2050, il y aura 700 millions de francophones, surtout grace a l\'Afrique ou la population croit rapidement.' },
    { emoji: '🌍', title: 'La francophonie en Afrique', content: 'L\'Afrique est le continent ou le francais est le plus parle : Senegal, Cote d\'Ivoire, RD Congo, Cameroun, Madagascar... L\'heritage de la colonisation, mais aussi un choix de cooperation.', highlights: ['Afrique : 60% des francophones', 'Langue officielle dans 21 pays africains', 'Langue d\'enseignement', 'Cooperation culturelle'], tip: 'Kinshasa (RD Congo) est la plus grande ville francophone du monde avec 17 millions d\'habitants, devant Paris !' },
    { emoji: '🤝', title: 'Les valeurs de la francophonie', content: 'La francophonie, c\'est plus qu\'une langue : c\'est des valeurs partagees (democratie, droits de l\'Homme, diversite culturelle) et une cooperation dans l\'education, la culture et l\'economie.', highlights: ['Langue commune', 'Valeurs democratiques', 'Echanges culturels', 'Cooperation educative'], tip: 'Le Sommet de la Francophonie reunit les chefs d\'Etat francophones tous les 2 ans. C\'est un moment de dialogue et de cooperation.' },
  ]},
  'geo-6e-2': { title: '6eme - Habiter des espaces contraints', pages: [
    { emoji: '🏔️', title: 'Habiter en montagne', content: 'Les montagnes posent des contraintes : pentes, froid, isolement. Les populations s\'adaptent : villages dans les vallees, terrasses agricoles, tourisme hivernal. Les Sherpas de l\'Himalaya vivent a plus de 4 000 m.', highlights: ['Contraintes : pentes, froid', 'Adaptation : villages en vallee', 'Tourisme : ski, randonnee', 'Risques : avalanches, glissements'], tip: 'Au Nepal, les Sherpas portent des charges de 30 kg sur le dos a 5 000 m d\'altitude. Ils sont adaptes a l\'altitude depuis des generations.' },
    { emoji: '🏜️', title: 'Habiter le desert', content: 'Les deserts chauds (Sahara) et froids (Arctique) sont des milieux extremes. L\'eau est rare, les temperatures extremes. Les habitants s\'adaptent : oasis, nomadisme, igloos.', highlights: ['Desert chaud : Sahara, 50°C', 'Desert froid : Arctique, -50°C', 'Eau : ressource vitale', 'Adaptation : nomadisme, oasis'], tip: 'Le Sahara est aussi grand que les Etats-Unis ! Pourtant, seulement 2,5 millions de personnes y vivent.' },
    { emoji: '🌋', title: 'Habiter dans une zone a risques', content: 'Volcans, seismes, inondations, typhons : des millions de personnes vivent dans des zones a risques. Le Japon subit seismes et tsunamis mais s\'est adapte avec des batiments parasismiques.', highlights: ['Volcans et seismes', 'Inondations et typhons', 'Prevention et adaptation', 'Construction parasismique'], tip: 'Le Japon subit 1 500 seismes par an ! Les batiments sont construits sur des amortisseurs qui absorbent les vibrations.' },
    { emoji: '🏝️', title: 'Habiter une ile', content: 'Les iles posent le defi de l\'isolement. Tout doit etre importe par bateau ou avion. Mais elles ont des atouts : peche, tourisme, biodiversite unique. Les petites iles sont menacees par la montee des eaux.', highlights: ['Isolement : tout a importer', 'Peche et tourisme', 'Biodiversite unique', 'Montee des eaux : menace'], tip: 'Les Maldives (ocean Indien) sont le pays le plus plat du monde : altitude moyenne de 1,5 m. La montee des eaux menace leur existence meme.' },
    { emoji: '🌿', title: 'Habiter la foret dense', content: 'L\'Amazonie, le Congo, l\'Asie du Sud-Est abritent des forets denses et humides. Les peuples autochtones y vivent en harmonie avec la nature. La deforestation menace ces ecosystemes essentiels.', highlights: ['Amazonie : poumon de la Terre', 'Peuples autochtones', 'Biodiversite immense', 'Deforestation : menace majeure'], tip: 'L\'Amazonie produit 20% de l\'oxygene mondial et abrite 10% des especes connues. La proteger est vital pour la planete.' },
  ]},
  'geo-6e-3': { title: '6eme - Repartition de la population', pages: [
    { emoji: '👥', title: '8 milliards d\'humains', content: 'La Terre compte 8 milliards d\'habitants en 2023. La population augmente surtout en Afrique et en Asie. Elle stagne ou diminue en Europe et au Japon.', highlights: ['8 milliards (2023)', 'Croissance surtout en Afrique', 'Stagnation en Europe', 'Baisse au Japon'], tip: 'La population mondiale a double en 50 ans (4 milliards en 1975, 8 milliards en 2023). Mais la croissance ralentit.' },
    { emoji: '📍', title: 'Ou vit-on ?', content: 'La population se concentre dans 3 grands foyers : Asie de l\'Est (Chine, Japon), Asie du Sud (Inde), Europe. Les deserts, les poles et les hautes montagnes sont quasi vides.', highlights: ['3 foyers principaux', 'Asie : 60% de la pop.', 'Deserts et poles : quasi vides', 'Densite : hab/km²'], tip: 'Le Bangladesh a une densite de 1 200 hab/km². La Mongolie : 2 hab/km². Un ecart de 600 fois !' },
    { emoji: '🏙️', title: 'L\'urbanisation', content: 'Plus de 55% des humains vivent en ville (contre 30% en 1950). Les megapoles (+ de 10 millions d\'habitants) se multiplient : Tokyo, Delhi, Shanghai, Sao Paulo, Mexico.', highlights: ['55% urbains en 2023', 'Megapoles : Tokyo 37M, Delhi 32M', 'Exode rural mondial', 'Bidonvilles dans les pays pauvres'], tip: 'Tokyo est la plus grande agglomeration du monde : 37 millions d\'habitants. C\'est plus que le Canada entier !' },
    { emoji: '📊', title: 'Densite et repartition', content: 'La densite de population = nombre d\'habitants / surface. Forte densite : villes, deltas, plaines fertiles. Faible densite : deserts, montagnes, forets. Les contraintes naturelles expliquent la repartition.', highlights: ['Densite = pop / surface', 'Forte : plaines, cotes, villes', 'Faible : deserts, montagnes', 'Facteurs : climat, eau, relief'], tip: 'La France a une densite de 120 hab/km² en moyenne. Mais Paris a 20 000 hab/km² et la Lozere seulement 15 !' },
    { emoji: '🌍', title: 'Defis de la population', content: 'La croissance demographique pose des defis : nourrir tout le monde, loger, eduquer, soigner, preserver l\'environnement. Le vieillissement de la population est un autre defi en Europe et au Japon.', highlights: ['Nourrir 8 milliards', 'Acces a l\'education et la sante', 'Vieillissement en Europe/Japon', 'Pression sur l\'environnement'], tip: 'Au Niger, 50% de la population a moins de 15 ans. Au Japon, 30% a plus de 65 ans. Des defis completement differents !' },
  ]},
  'geo-6e-4': { title: '6eme - Habiter un espace agricole', pages: [
    { emoji: '🌾', title: 'L\'agriculture dans le monde', content: 'L\'agriculture nourrit l\'humanite. Elle occupe 40% des terres emergees. Deux types : agriculture vivriere (nourrir sa famille) et agriculture commerciale (vendre sur les marches).', highlights: ['40% des terres emergees', 'Vivriere : pour se nourrir', 'Commerciale : pour vendre', '800 millions d\'agriculteurs'], tip: 'En Afrique, 60% de la population travaille dans l\'agriculture. En France, seulement 3%. La mecanisation change tout.' },
    { emoji: '🚜', title: 'Agriculture intensive', content: 'L\'agriculture intensive utilise machines, engrais, pesticides pour produire beaucoup sur peu de surface. Elle domine en Europe, Amerique du Nord. Elle nourrit mais pollue.', highlights: ['Machines et technologies', 'Engrais et pesticides', 'Rendements eleves', 'Pollution eau et sol'], tip: 'Un agriculteur americain nourrit en moyenne 155 personnes. Un agriculteur africain nourrit en moyenne 4 personnes.' },
    { emoji: '🌿', title: 'Agriculture vivriere', content: 'L\'agriculture vivriere nourrit la famille du paysan avec peu de moyens. Predominante en Afrique et Asie du Sud. Outils manuels, faibles rendements, vulnerabilite climatique.', highlights: ['Pour nourrir sa famille', 'Outils manuels', 'Faibles rendements', 'Vulnerabilite au climat'], tip: 'Les femmes representent 50% des agriculteurs dans les pays en developpement mais possedent moins de 15% des terres.' },
    { emoji: '🌱', title: 'L\'agriculture durable', content: 'L\'agriculture bio, l\'agroecologie, les circuits courts cherchent a produire en respectant l\'environnement. Moins de pesticides, rotation des cultures, respect des sols.', highlights: ['Agriculture biologique', 'Agroecologie', 'Circuits courts : du producteur au consommateur', 'Respect des sols et de l\'eau'], tip: 'En France, l\'agriculture bio represente 10% des surfaces cultivees et sa part augmente chaque annee.' },
    { emoji: '🍽️', title: 'Nourrir l\'humanite', content: 'Le defi : nourrir 10 milliards d\'humains en 2050 tout en preservant la planete. Reduire le gaspillage (1/3 de la nourriture est jetee), mieux repartir, produire durablement.', highlights: ['10 milliards en 2050', '1/3 de la nourriture gaspillee', '800 millions de personnes sous-alimentees', 'Produire plus avec moins'], tip: 'En France, chaque personne jette 30 kg de nourriture par an. A l\'echelle mondiale, c\'est 1,3 milliard de tonnes gaspillees !' },
  ]},
  'geo-6e-5': { title: '6eme - Habiter un littoral', pages: [
    { emoji: '🏖️', title: 'Les littoraux touristiques', content: 'Les cotes attirent les touristes : soleil, plage, baignade. Le tourisme balneaire transforme les littoraux : hotels, restaurants, ports de plaisance. Mais il menace les ecosystemes fragiles.', highlights: ['Tourisme de masse sur les cotes', 'Amenagements : hotels, ports', 'Pression sur l\'environnement', 'Erosion et pollution'], tip: 'En Mediterranee, 250 millions de touristes visitent les cotes chaque ete. C\'est 7 fois la population des pays riverains !' },
    { emoji: '🚢', title: 'Les littoraux industrialo-portuaires', content: 'Les grands ports sont des hubs du commerce mondial : Rotterdam, Shanghai, Singapour. Les ZIP (zones industrialo-portuaires) combinent port, usines et stockage. 90% du commerce mondial passe par la mer.', highlights: ['90% du commerce par la mer', 'Conteneurs : revolution logistique', 'ZIP : port + industrie', 'Mondialisation des echanges'], tip: 'Un porte-conteneurs geant peut transporter 24 000 conteneurs. Bout a bout, ils feraient une ligne de 145 km !' },
    { emoji: '🐠', title: 'Les littoraux et la peche', content: 'Les mers nourrissent des millions de personnes. La peche artisanale emploie 90% des pecheurs du monde. La surpeche menace les stocks de poissons. L\'aquaculture se developpe.', highlights: ['Peche artisanale : 90% des pecheurs', 'Surpeche : menace les stocks', 'Aquaculture en croissance', 'Quotas de peche pour proteger'], tip: '90% des grands poissons predateurs (thon, espadon) ont disparu depuis 1950 a cause de la surpeche. Les quotas sont essentiels.' },
    { emoji: '🌊', title: 'Les risques littoraux', content: 'Les littoraux sont menaces : erosion, submersion, tempetes, tsunamis, montee des eaux. Le rechauffement climatique aggrave ces risques. Des millions de personnes sont concernees.', highlights: ['Erosion : recul des cotes', 'Submersion : montee des eaux', 'Tempetes et tsunamis', '1 milliard de personnes menacees'], tip: 'La montee des eaux pourrait atteindre 1 m d\'ici 2100. Des villes comme Miami, Venise, Bangkok seraient partiellement submergees.' },
    { emoji: '🌿', title: 'Proteger les littoraux', content: 'Proteger les littoraux : Conservatoire du littoral, reserves marines, recul strategique (reculer les constructions). L\'equilibre entre exploitation et preservation est le defi majeur.', highlights: ['Conservatoire du littoral', 'Reserves marines', 'Recul strategique', 'Gestion integree des zones cotieres'], tip: 'Le Conservatoire du littoral protege 200 000 hectares de cotes en France. Ces espaces sont ouverts au public mais proteges de la construction.' },
  ]},
  'geo-5e-2': { title: '5eme - Richesse et pauvrete', pages: [
    { emoji: '💰', title: 'Les inegalites dans le monde', content: 'Le monde est tres inegal. Les 10% les plus riches possedent 76% des richesses mondiales. Les pays du Nord sont globalement plus riches que ceux du Sud. Mais les inegalites existent aussi a l\'interieur des pays.', highlights: ['10% possedent 76% des richesses', 'Inegalites Nord-Sud', 'IDH : indice de developpement humain', 'Inegalites aussi dans les pays riches'], tip: 'L\'IDH (Indice de Developpement Humain) combine esperance de vie, education et revenu. La Norvege est 1ere, le Niger dernier.' },
    { emoji: '📊', title: 'Mesurer la richesse', content: 'Le PIB (Produit Interieur Brut) mesure la richesse produite par un pays. Le PIB par habitant permet de comparer : Luxembourg 130 000$/hab, France 40 000$, Niger 500$. Mais le PIB ne mesure pas le bonheur.', highlights: ['PIB : richesse produite', 'PIB/habitant : pour comparer', 'IDH : plus complet', 'Le PIB ne mesure pas le bien-etre'], tip: 'Le Bhoutan a invente le BNB (Bonheur National Brut) pour mesurer le bien-etre de sa population au-dela de la richesse economique.' },
    { emoji: '🏚️', title: 'La pauvrete dans le monde', content: '700 millions de personnes vivent avec moins de 2$/jour. La pauvrete se manifeste par la faim, le manque d\'eau potable, l\'absence d\'ecole et de soins. L\'Afrique subsaharienne et l\'Asie du Sud sont les plus touchees.', highlights: ['700 millions en extreme pauvrete', 'Faim, eau, sante, education', 'Afrique subsaharienne : plus touchee', 'Progres : pauvrete en baisse'], tip: 'En 30 ans, la pauvrete extreme a ete divisee par 3. En 1990, 36% de la pop. mondiale etait pauvre. En 2023, 9%. C\'est un progres immense.' },
    { emoji: '🏗️', title: 'Le developpement', content: 'Le developpement, c\'est l\'amelioration des conditions de vie : sante, education, alimentation, logement. L\'aide au developpement, le commerce equitable et l\'education sont des leviers essentiels.', highlights: ['Sante : vaccination, hopitaux', 'Education : ecoles, alphabetisation', 'Commerce equitable', 'Aide internationale'], tip: 'L\'education des filles est le levier le plus puissant du developpement. Une fille eduquee aura moins d\'enfants, mieux nourris et en meilleure sante.' },
    { emoji: '🌍', title: 'Agir contre les inegalites', content: 'Les 17 ODD de l\'ONU visent a reduire les inegalites d\'ici 2030 : fin de la pauvrete, faim zero, education pour tous, egalite des genres. Chacun peut agir : consommer equitable, donner, s\'informer.', highlights: ['17 ODD de l\'ONU', 'Commerce equitable', 'Associations humanitaires', 'S\'informer et sensibiliser'], tip: 'Acheter du chocolat equitable assure un prix juste aux producteurs de cacao en Afrique. Ton achat peut changer des vies !' },
  ]},
  'geo-5e-3': { title: '5eme - L\'eau dans le monde', pages: [
    { emoji: '💧', title: 'L\'eau sur Terre', content: 'La Terre est la planete bleue : 71% de sa surface est couverte d\'eau. Mais 97% est de l\'eau salee ! L\'eau douce (3%) est surtout dans les glaciers. Seulement 1% est directement utilisable.', highlights: ['97% eau salee', '3% eau douce', '1% accessible', 'Repartition tres inegale'], tip: 'Si toute l\'eau de la Terre tenait dans un seau de 10 litres, l\'eau douce accessible serait l\'equivalent d\'une cuillere a cafe.' },
    { emoji: '🚰', title: 'L\'acces a l\'eau', content: '2 milliards de personnes n\'ont pas acces a l\'eau potable. L\'eau est inegalement repartie : abondante en zones tropicales humides, rare dans les zones arides. Le manque d\'eau est source de conflits.', highlights: ['2 milliards sans eau potable', 'Inegalites d\'acces', 'Zones arides : stress hydrique', 'Eau : source de conflits'], tip: 'Un Americain consomme 300 L/jour, un Francais 150 L, un Africain 20 L. L\'inegalite d\'acces a l\'eau est enorme.' },
    { emoji: '🌾', title: 'Les usages de l\'eau', content: 'L\'agriculture utilise 70% de l\'eau douce mondiale (irrigation). L\'industrie 20%. Les usages domestiques 10%. Economiser l\'eau, c\'est surtout changer nos modes de production.', highlights: ['Agriculture : 70%', 'Industrie : 20%', 'Domestique : 10%', 'Irrigation : plus gros consommateur'], tip: 'Pour produire 1 kg de boeuf, il faut 15 000 L d\'eau (alimentation du betail, abreuvement). Pour 1 kg de ble : 1 500 L. Manger moins de viande economise de l\'eau.' },
    { emoji: '⚠️', title: 'La pollution de l\'eau', content: 'L\'eau est polluee par l\'agriculture (pesticides, engrais), l\'industrie (produits chimiques) et les eaux usees non traitees. 80% des eaux usees dans le monde ne sont pas traitees.', highlights: ['Pesticides et engrais', 'Rejets industriels', 'Eaux usees non traitees', 'Plastiques dans les oceans'], tip: '8 millions de tonnes de plastique finissent dans les oceans chaque annee. Il y a un "7e continent" de plastique dans le Pacifique.' },
    { emoji: '🌍', title: 'L\'eau, enjeu du XXIe siecle', content: 'Avec le rechauffement climatique et la croissance demographique, l\'eau sera l\'enjeu majeur du siecle. Solutions : dessalement, recyclage, economies, partage equitable.', highlights: ['Rechauffement : secheresses', 'Croissance demographique', 'Dessalement de l\'eau de mer', 'Partage equitable indispensable'], tip: 'Le dessalement de l\'eau de mer est couteux en energie mais devient indispensable. L\'Arabie saoudite produit 50% de son eau potable ainsi.' },
  ]},
  'geo-5e-4': { title: '5eme - Energie et changement climatique', pages: [
    { emoji: '⚡', title: 'Les sources d\'energie', content: 'Le monde consomme surtout des energies fossiles : petrole (31%), gaz (24%), charbon (27%). Ces energies sont limitees et polluantes. Les renouvelables (18%) progressent : solaire, eolien, hydraulique.', highlights: ['Fossiles : 82% de l\'energie', 'Petrole, gaz, charbon', 'Renouvelables : 18%', 'Nucleaire : 4%'], tip: 'Au rythme actuel, les reserves de petrole dureraient 50 ans, le gaz 60 ans, le charbon 130 ans. Il est urgent de changer.' },
    { emoji: '🌡️', title: 'Le changement climatique', content: 'La combustion des energies fossiles libere du CO2 qui rechauffe la planete (effet de serre). +1,2°C depuis 1900. Consequences : fonte des glaces, montee des eaux, evenements extremes.', highlights: ['+1,2°C depuis 1900', 'CO2 : gaz a effet de serre', 'Fonte des glaciers et banquise', 'Evenements extremes plus frequents'], tip: '+1,5°C est le seuil a ne pas depasser selon le GIEC. Au-dela, les consequences sont irreversibles : disparition d\'especes, submersion de villes.' },
    { emoji: '☀️', title: 'Les energies renouvelables', content: 'Solaire, eolien, hydraulique, biomasse, geothermie : les renouvelables ne s\'epuisent pas et polluent peu. Leur cout baisse rapidement. Le solaire a ete divise par 10 en 10 ans.', highlights: ['Solaire : energie du soleil', 'Eolien : force du vent', 'Hydraulique : barrages', 'Biomasse : matieres organiques'], tip: 'Le prix du solaire a baisse de 90% en 10 ans. Dans beaucoup de pays, c\'est desormais la source d\'electricite la moins chere.' },
    { emoji: '🏭', title: 'La transition energetique', content: 'La transition energetique, c\'est passer des fossiles aux renouvelables et au nucleaire bas carbone. Les pays s\'engagent (Accord de Paris, 2015) a limiter le rechauffement a +1,5°C.', highlights: ['Accord de Paris (2015)', 'Limiter a +1,5°C', 'Sortir des fossiles', 'Efficacite energetique'], tip: 'L\'Accord de Paris a ete signe par 196 pays. C\'est le premier accord universel sur le climat.' },
    { emoji: '🌿', title: 'Agir pour le climat', content: 'Chacun peut agir : economies d\'energie, transports doux, alimentation locale, tri des dechets. Les decisions collectives (politiques, lois, investissements) sont aussi essentielles.', highlights: ['Economies d\'energie', 'Mobilite douce', 'Alimentation durable', 'Engagement citoyen'], tip: 'Manger local et de saison, prendre le velo, baisser le chauffage : chaque geste compte. Et voter pour des politiques climatiques aussi !' },
  ]},
  'geo-5e-5': { title: '5eme - Risques et nourrir l\'humanite', pages: [
    { emoji: '🌋', title: 'Les risques naturels', content: 'Seismes, volcans, inondations, cyclones, secheresses : les risques naturels menacent des milliards de personnes. Ils sont aggraves par le changement climatique et l\'urbanisation.', highlights: ['Seismes et volcans : tectonique', 'Inondations et cyclones : climat', 'Secheresses : rechauffement', '150 millions de personnes touchees/an'], tip: 'Les pays pauvres sont les plus vulnerables car ils ont moins de moyens de prevention et de reconstruction.' },
    { emoji: '🏗️', title: 'Prevention et adaptation', content: 'Se proteger des risques : constructions parasismiques, digues, alertes meteo, plans d\'evacuation. La prevention sauve des vies. Le Japon investit massivement dans la prevention sismique.', highlights: ['Constructions adaptees', 'Systemes d\'alerte', 'Plans d\'evacuation', 'Education aux risques'], tip: 'En France, le plan ORSEC organise les secours en cas de catastrophe. Chaque commune a risque doit avoir un PCS (Plan Communal de Sauvegarde).' },
    { emoji: '🍽️', title: 'Nourrir 8 milliards d\'humains', content: 'La Terre produit assez pour nourrir tout le monde, mais 800 millions souffrent de la faim. Le probleme est la repartition, le gaspillage (1/3 jete) et les inegalites d\'acces.', highlights: ['Assez de nourriture produite', '800 millions de sous-alimentes', '1/3 de la nourriture gaspillee', 'Inegalites d\'acces'], tip: 'Si on eliminait le gaspillage alimentaire mondial, on pourrait nourrir 2 milliards de personnes supplementaires.' },
    { emoji: '🌾', title: 'L\'agriculture de demain', content: 'Nourrir 10 milliards d\'humains en 2050 de maniere durable : agroecologie, agriculture de precision, circuits courts, reduction du gaspillage, diversification alimentaire.', highlights: ['Agroecologie : respecter la nature', 'Agriculture de precision : technologie', 'Circuits courts : local', 'Moins de viande, plus de vegetaux'], tip: 'Les insectes sont une source de proteines tres efficace : il faut 10x moins d\'eau et de terre que pour le boeuf. 2 milliards de personnes en mangent deja.' },
    { emoji: '🌍', title: 'La securite alimentaire', content: 'La securite alimentaire, c\'est l\'acces pour tous a une nourriture suffisante, saine et nutritive. Les conflits, le climat et la pauvrete sont les 3 principales menaces a la securite alimentaire.', highlights: ['Acces a une nourriture suffisante', 'Conflits : 1re cause de famine', 'Climat : secheresses, inondations', 'Pauvrete : manque de moyens'], tip: 'Les guerres sont la 1re cause de famine dans le monde. La paix est le prealable a la securite alimentaire.' },
  ]},
};

// Insert each lesson after the corresponding "-1" lesson
for (const [key, lesson] of Object.entries(newLessons)) {
  // Check if this lesson already exists
  if (content.includes(`'${key}':`)) {
    console.log(`Skipping ${key} (already exists)`);
    continue;
  }

  // Find the "-1" key for same subject/grade
  const parts = key.match(/^(.*)-(\d+)$/);
  if (!parts) continue;
  const baseKey = parts[1] + '-1';

  // Find the end of the "-1" lesson block
  const basePattern = `'${baseKey}':`;
  const baseIdx = content.indexOf(basePattern);
  if (baseIdx === -1) {
    console.log(`Cannot find base key ${baseKey} for ${key}`);
    continue;
  }

  // Find the proper insertion point - after the closing of the current entry
  // We need to find the next top-level entry after the base key
  const afterBase = content.indexOf(basePattern) + basePattern.length;

  // Build the lesson content string
  let lessonStr = `  '${key}': {\n    title: '${lesson.title}',\n    pages: [\n`;
  for (const page of lesson.pages) {
    const c = (s) => s.replace(/'/g, "\\'");
    lessonStr += `      { emoji: '${page.emoji}', title: '${c(page.title)}', content: '${c(page.content)}', highlights: [${page.highlights.map(h => `'${c(h)}'`).join(', ')}], tip: '${c(page.tip)}'${page.example ? `, example: '${c(page.example)}'` : ''} },\n`;
  }
  lessonStr += `    ],\n  },\n`;

  // Insert after the previous level for the same subject/grade
  // Find the right insertion point
  const prevNum = parseInt(parts[2]) - 1;
  const prevKey = parts[1] + '-' + prevNum;
  const prevPattern = `'${prevKey}':`;
  const prevIdx = content.indexOf(prevPattern);

  if (prevIdx === -1) {
    console.log(`Cannot find previous key ${prevKey} for ${key}`);
    continue;
  }

  // Find the end of the previous lesson block (next top-level key)
  let searchFrom = prevIdx + prevPattern.length;
  // Find next "  '" or "  //" pattern
  const nextEntry = content.indexOf("\n  '", searchFrom);
  const nextComment = content.indexOf("\n  //", searchFrom);
  let insertAt;
  if (nextEntry === -1 && nextComment === -1) {
    insertAt = content.lastIndexOf('}');
  } else if (nextEntry === -1) {
    insertAt = nextComment + 1;
  } else if (nextComment === -1) {
    insertAt = nextEntry + 1;
  } else {
    insertAt = Math.min(nextEntry, nextComment) + 1;
  }

  content = content.slice(0, insertAt) + lessonStr + content.slice(insertAt);
  console.log(`Added ${key}`);
}

fs.writeFileSync(file, content);
console.log('Done! Checking count...');

// Count lessons
const matches = content.match(/'[a-z]+-[a-z0-9]+-\d+':/g);
console.log(`Total lessons: ${matches ? matches.length : 0}`);
